import Foundation

final class LocalizationManager {
    static let shared = LocalizationManager()

    private var currentLanguage: GameLanguage = .english
    private var strings: [String: String] = [:]

    private init() {
        loadLanguage(.english)
    }

    var language: GameLanguage {
        return currentLanguage
    }

    func setLanguage(_ language: GameLanguage) {
        currentLanguage = language
        loadLanguage(language)
        UserDefaults.standard.set(language.rawValue, forKey: "game_language")
    }

    func loadSavedLanguage() {
        if let saved = UserDefaults.standard.string(forKey: "game_language"),
           let lang = GameLanguage(rawValue: saved) {
            setLanguage(lang)
        } else {
            currentLanguage = .english
            loadLanguage(.english)
        }
    }

    var hasSelectedLanguage: Bool {
        return UserDefaults.standard.string(forKey: "game_language") != nil
    }

    func localize(_ key: String) -> String {
        return strings[key] ?? key
    }

    private func loadLanguage(_ language: GameLanguage) {
        switch language {
        case .portuguese:
            strings = Self.portugueseStrings
        case .english:
            strings = Self.englishStrings
        }
    }

    // MARK: - Portuguese Strings
    static var portugueseStrings: [String: String] = [
        // Menu
        "menu.start": "Iniciar Jornada",
        "menu.continue": "Continuar Jornada",
        "menu.inventory": "Inventário",
        "menu.shop": "Loja",
        "menu.achievements": "Conquistas",
        "menu.ranking": "Ranking",
        "menu.pvp": "PvP Arena",
        "menu.clans": "Clãs",
        "menu.challenges": "Desafios Semanais",
        "menu.settings": "Configurações",
        "menu.characters": "Personagens",
        "menu.inventory_list": "Meus Itens",
        "menu.subtitle": "Do pasto ao trono",
        "menu.journey_badge": "JORNADA",
        "menu.chapter1": "Capítulo 1",
        "menu.prepare_david": "Prepare Davi.",
        "menu.battles_won": "%d vitórias, %d estrelas",
        "menu.progress": "Progresso",
        "menu.actions": "AÇÕES",
        "inventory.equipped": "Equipado",
        "inventory.equipped_short": "Eq.",
        "inventory.empty": "Nenhum item no inventário",
        "inventory.empty_slot": "Vazio",
        "inventory.item_count.one": "%d item",
        "inventory.item_count.many": "%d itens",
        "battle.blessing.choose": "Escolha uma bênção",
        "battle.blessing.fallback": "Bênção",
        "battle.blessing.desc_fallback": "Melhoria ativa",
        "battle.blessing.strength": "Bênção de Força",
        "battle.blessing.strength.desc": "+15% Dano",
        "battle.blessing.faith_shield": "Escudo da Fé",
        "battle.blessing.faith_shield.desc": "+10 Armadura",
        "battle.blessing.swift_hands": "Mãos Ágeis",
        "battle.blessing.swift_hands.desc": "+15% Vel. Ataque",
        "battle.blessing.bronze_skin": "Pele de Bronze",
        "battle.blessing.bronze_skin.desc": "+20 HP Máx",
        "battle.blessing.eagle_eye": "Olho de Águia",
        "battle.blessing.eagle_eye.desc": "+10% Crítico",

        // Language Selection
        "lang.title": "Escolha seu idioma",
        "lang.select": "Selecionar",

        // Login
        "login.title": "Davi: O Ungido",
        "login.google": "Entrar com Google",
        "login.apple": "Entrar com Apple",
        "login.loading": "Carregando...",
        "login.loading_google": "Entrando com Google...",
        "login.loading_apple": "Entrando com Apple...",

        // Maps
        "map.stage": "Fase",
        "map.bethlehem_fields": "Campos de Belém",
        "map.valley_of_elah": "Vale de Elá",
        "map.saul_court": "Corte de Saul",
        "map.en_gedi": "Deserto de En-Gedi",
        "map.philistine_land": "Terra dos Filisteus",
        "map.jerusalem_siege": "Cerco de Jerusalém",
        "map.throne_israel": "Trono de Israel",

        // Battles Map 1
        "battle.wolf_pack": "Alcateia dos Campos",
        "battle.night_invaders": "Invasores Noturnos",
        "battle.mountain_trail": "Trilha da Montanha",
        "battle.lion_boss": "O Leão de Belém",

        // Battles Map 2
        "battle.mountain_bear": "O Urso das Montanhas",
        "battle.philistine_scouts": "Batedores Filisteus",
        "battle.advance_guard": "Guarda Avançada",
        "battle.goliath_boss": "Golias, o Gigante",

        // Battles Map 3
        "battle.royal_hall": "Salão Real de Saul",
        "battle.conspiracy": "Conspiração no Palácio",
        "battle.betrayal": "A Traição de Saul",
        "battle.saul_boss": "Saul, o Rei Atormentado",
        "battle.burning_dunes": "Dunas Ardentes",
        "battle.cave_path": "Caminho da Caverna",
        "battle.en_gedi_oasis": "Oásis de En-Gedi",
        "battle.general_boss": "General de Saul",
        "battle.philistine_border": "Fronteira Filisteia",
        "battle.road_to_gath": "Estrada para Gate",
        "battle.war_camp": "Acampamento de Guerra",
        "battle.prince_boss": "Príncipe Filisteu",
        "battle.jebus_walls": "Muralhas de Jebus",
        "battle.water_tunnels": "Túneis de Água",
        "battle.city_gates": "Portões da Cidade",
        "battle.commander_boss": "Comandante Jebuseu",
        "battle.jerusalem_rebellion": "Rebelião em Jerusalém",
        "battle.kidron_path": "Caminho do Cedrom",
        "battle.civil_war": "Guerra Civil",
        "battle.absalom_boss": "Absalão, o Rebelde",

        // Enemies
        "enemy.grey_wolf": "Lobo Cinzento",
        "enemy.alpha_wolf": "Lobo Alfa",
        "enemy.rabid_fox": "Raposa Raivosa",
        "enemy.hungry_jackal": "Chacal Faminto",
        "enemy.wild_boar": "Javali Selvagem",
        "enemy.venomous_snake": "Serpente Venenosa",
        "enemy.hunting_eagle": "Águia Caçadora",
        "enemy.giant_scorpion": "Escorpião Gigante",
        "enemy.pack_hyena": "Hiena Matilheira",
        "enemy.hyena_pup": "Hiena Filhote",
        "enemy.lion_boss": "Leão de Belém",
        "enemy.bear_cub": "Filhote de Urso",
        "enemy.brown_bear": "Urso Pardo",
        "enemy.goliath": "Golias",
        "enemy.philistine_scout_spear": "Batedor Filisteu (Lança)",
        "enemy.philistine_scout_bow": "Batedor Filisteu (Arco)",
        "enemy.philistine_scout_shield": "Batedor Filisteu (Escudo)",
        "enemy.philistine_soldier": "Soldado Filisteu",
        "enemy.philistine_archer": "Arqueiro Filisteu",
        "enemy.philistine_elite": "Soldado Filisteu Elite",
        "enemy.philistine_healer": "Curandeiro Filisteu",
        "enemy.saul_guard": "Guarda Real",
        "enemy.saul_archer": "Arqueiro Real",
        "enemy.saul_spearman": "Lanceiro Real",
        "enemy.saul_advisor": "Conselheiro Real",
        "enemy.saul_mad": "Rei Saul",
        "enemy.saul_general": "General de Saul",
        "enemy.desert_bandit": "Bandido do Deserto",
        "enemy.bandit_archer": "Arqueiro Bandido",
        "enemy.giant_spider": "Aranha Gigante",
        "enemy.desert_stalker": "Espreitador do Deserto",
        "enemy.philistine_heavy_guard": "Guarda Pesado Filisteu",
        "enemy.philistine_war_archer": "Arqueiro de Guerra Filisteu",
        "enemy.philistine_giant": "Gigante Filisteu",
        "enemy.philistine_priest": "Sacerdote Filisteu",
        "enemy.philistine_prince": "Príncipe Filisteu",
        "enemy.jebusite_defender": "Defensor Jebuseu",
        "enemy.jebusite_slinger": "Fundibulário Jebuseu",
        "enemy.jebusite_elite": "Elite Jebuseia",
        "enemy.jebusite_shaman": "Xamã Jebuseu",
        "enemy.jebusite_commander": "Comandante Jebuseu",
        "enemy.absalom_rebel": "Rebelde de Absalão",
        "enemy.absalom_assassin": "Assassino de Absalão",
        "enemy.absalom_knight": "Cavaleiro de Absalão",
        "enemy.absalom_tactician": "Estrategista de Absalão",
        "enemy.absalom": "Absalão",

        // Food
        "food.barley_bread": "Pão de Cevada",
        "food.water_skin": "Água para Beber",
        "food.grapes": "Cacho de Uvas",
        "food.grape_juice": "Suco de Uva",
        "food.fresh_figs": "Figos Frescos",
        "food.dried_figs": "Figos Secos",
        "food.olives": "Azeitonas em Azeite",
        "food.honey_bread": "Pão com Mel",
        "food.pomegranate": "Romã",
        "food.goat_cheese": "Queijo de Cabra",
        "food.dates": "Tâmaras",
        "food.cooked_lentils": "Lentilhas Cozidas",
        "food.roasted_fish": "Peixe Assado",
        "food.raisin_cake": "Bolo de Passas",
        "food.roasted_lamb": "Cordeiro Assado",
        "food.manna": "Pão dos Anjos (Maná)",
        "food.kings_feast": "Festa do Rei",
        "food.celestial_banquet": "Banquete Celestial",
        "food.water_skin.buff": "+3% Esquiva por 8s",
        "food.grape_juice.buff": "+5% Chance Crítica por 10s",
        "food.dried_figs.buff": "Remove veneno",
        "food.olives.buff": "+5% Esquiva por 10s",
        "food.pomegranate.buff": "+10% Vel. Ataque por 8s",
        "food.goat_cheese.buff": "+5 Armadura por 10s",
        "food.dates.buff": "+8% Chance Crítica por 10s",
        "food.roasted_fish.buff": "+3% Roubo de Vida por 15s",
        "food.raisin_cake.buff": "Remove debuffs",
        "food.roasted_lamb.buff": "+10% Dano por 10s",
        "food.manna.buff": "+5% todos atributos por 10s",
        "food.kings_feast.buff": "+15% Dano, +10 Armadura por 12s",
        "food.celestial_banquet.buff": "Cura completa + todos buffs por 8s",

        // Characters
        "character.davi": "Davi",
        "character.bigJ": "JV",
        "character.sansao": "Sansão",
        "character.josue": "FaithTech",
        "character.debora": "Débora",
        "character.elias": "Elias",
        "character.gideao": "Gideão",
        "character.stats_title": "Ficha do Personagem",
        "character.passive_bonus": "Bônus passivo",
        "character.active": "ATIVO",
        "character.unlocked": "LIBERADO",
        "character.locked": "BLOQUEADO",
        "character.select": "Selecionar",
        "character.required_map": "Requer fase",
        "character.balanced": "Equilibrado",
        "character.unlocked_message": "Personagem liberado na sua lista.",
        "character.selected_message": "Personagem selecionado para a jornada.",
        "stat.hp": "HP",
        "stat.damage": "Dano",
        "stat.damage_bonus": "Dano",
        "stat.armor": "Armadura",
        "stat.crit_chance": "Crítico",
        "stat.crit_damage": "Dano Crítico",
        "stat.attack_speed": "Vel. Ataque",
        "stat.life_steal": "Roubo de Vida",
        "stat.dodge_melee": "Esquiva Corpo",
        "stat.dodge_ranged": "Esquiva Dist.",
        "stat.run_speed": "Velocidade",

        // HUD
        "hud.attack": "ATAQUE",
        "hud.defense": "DEFESA",
        "hud.dodge": "ESQUIVA",
        "hud.damage": "Dano",
        "hud.crit_chance": "Chance Crítica",
        "hud.crit_damage": "Dano Crítico",
        "hud.hp_max": "HP Máx",
        "hud.max_armor": "Máx Armadura",
        "hud.melee": "Corpo a corpo",
        "hud.ranged": "À distância",
        "hud.victory": "VITÓRIA!",
        "hud.defeat": "DERROTA",
        "hud.level": "Nível",
        "hud.gold": "Ouro",
        "hud.rubies": "Rubis",
        "battle.defeat_hint": "Reforce Davi e tente novamente",
        "battle.partial_reward": "Você ganhou",

        // Item Actions & Slots
        "item.action.equip": "Equipar",
        "item.action.unequip": "Desequipar",
        "item.type": "Tipo",
        "shop.owned": "Possui",
        "shop.food": "Comida",
        "shop.filter.all": "Todos",
        "shop.filter.weapon": "Arma",
        "shop.filter.shield": "Escudo",
        "shop.chests": "Recompensas",
        "shop.rewards": "Recompensas",
        "shop.reward.battle.title": "Batalhe",
        "shop.reward.battle.desc": "Vença fases para ganhar ouro, XP e chance de item.",
        "shop.reward.items.title": "Itens",
        "shop.reward.items.desc": "Drops vêm como recompensa de fase, não por compra aleatória.",
        "shop.reward.shop.title": "Loja Clara",
        "shop.reward.shop.desc": "Compre equipamentos, comida e personagens específicos.",
        "shop.reward.footer": "Não há baús compráveis ou sorteios pagos. Todo ouro é ganho jogando.",
        "shop.chest.common": "Recompensa Comum",
        "shop.chest.rare": "Recompensa Rara",
        "shop.chest.legendary": "Recompensa Lendária",
        "shop.chest.common.desc": "Bônus de batalha",
        "shop.chest.rare.desc": "Drop de fase",
        "shop.chest.legendary.desc": "Conquista rara",
        "shop.chest.reward": "Você ganhou",
        "shop.chest.empty": "Sem itens novos",
        "shop.chest.empty.desc": "Você já possui todos os itens possíveis.",
        "shop.not_enough_gold": "Ouro insuficiente",
        "shop.not_enough_gold.desc": "Jogue batalhas para ganhar mais ouro.",
        "shop.sell.title": "Vender item",
        "shop.sell.confirm": "Vender por",
        "shop.sell.done": "Vendido",
        "shop.sell.done.desc": "%@ vendido por %d ouro.",
        "item.rarity.common": "Comum",
        "item.rarity.uncommon": "Incomum",
        "item.rarity.rare": "Raro",
        "item.rarity.epic": "Épico",
        "item.rarity.legendary": "Lendário",
        "item.slot.head": "Cabeça",
        "item.slot.body": "Corpo",
        "item.slot.feet": "Pés",
        "item.slot.waist": "Cinto",
        "item.slot.mainHand": "Mão Principal",
        "item.slot.offHand": "Mão Secundária",
        "item.slot.twoHand": "Duas Mãos",
        "item.slot.necklace": "Colar",
        "item.slot.ring1": "Anel 1",
        "item.slot.ring2": "Anel 2",
        "item.slot.gloves": "Luvas",
        "item.slot.short.head": "CAB",
        "item.slot.short.body": "COR",
        "item.slot.short.feet": "PES",
        "item.slot.short.waist": "CIN",
        "item.slot.short.mainHand": "M1",
        "item.slot.short.offHand": "M2",
        "item.slot.short.twoHand": "2M",
        "item.slot.short.necklace": "COL",
        "item.slot.short.ring1": "A1",
        "item.slot.short.ring2": "A2",
        "item.slot.short.gloves": "LUV",

        // Abilities
        "ability.bite": "Mordida",
        "ability.bite.desc": "Dano + sangramento leve",
        "ability.howl": "Uivo",
        "ability.howl.desc": "Buff ataque aliados +20%",
        "ability.charge": "Investida",
        "ability.charge.desc": "Dano em área + stun 1s",
        "ability.venom": "Veneno",
        "ability.venom.desc": "Dano por tempo 3s",
        "ability.dive": "Mergulho",
        "ability.dive.desc": "Ataque aéreo, ignora armadura",
        "ability.sting": "Ferrão",
        "ability.sting.desc": "Veneno + slow",
        "ability.summon_pup": "Invocar Filhote",
        "ability.summon_pup.desc": "Invoca 1 Hiena Filhote",
        "ability.paw_swipe": "Patada",
        "ability.paw_swipe.desc": "Golpe de garra",
        "ability.roar": "Rugido",
        "ability.roar.desc": "Reduz ataque -15% por 5s",
        "ability.death_leap": "Salto Mortal",
        "ability.death_leap.desc": "Dano massivo + stun",
        "ability.bear_hug": "Abraço de Urso",
        "ability.bear_hug.desc": "Agarra e causa dano contínuo 3s",
        "ability.claw_strike": "Golpe de Garra",
        "ability.claw_strike.desc": "Dano + reduz armadura -5",
        "ability.block": "Bloqueio",
        "ability.block.desc": "+50% armadura temporária",
        "ability.fire_arrow": "Flecha Flamejante",
        "ability.fire_arrow.desc": "DoT 2s",
        "ability.counter": "Contra-Ataque",
        "ability.counter.desc": "Reflete 20% dano",
        "ability.heal_allies": "Curar Aliados",
        "ability.heal_allies.desc": "+15 HP aliados a cada 5s",
        "ability.spear_throw": "Lançamento de Lança",
        "ability.spear_throw.desc": "Dano alto à distância",
        "ability.giant_shield": "Escudo Gigante",
        "ability.giant_shield.desc": "Bloqueia próximo ataque",
        "ability.stomp": "Pisotão",
        "ability.stomp.desc": "AoE + stun 2s",
        "ability.giant_fury": "Fúria do Gigante",
        "ability.giant_fury.desc": "Dano +30% + investida",
        "ability.javelin_throw": "Arremesso de Dardo",
        "ability.javelin_throw.desc": "Dano perfurante à distância",
        "ability.mad_fury": "Fúria Insana",
        "ability.mad_fury.desc": "Ataques mais rápidos por pouco tempo",
        "ability.strategic_strike": "Golpe Estratégico",
        "ability.strategic_strike.desc": "Dano alto contra alvos enfraquecidos",
        "ability.call_reinforcements": "Chamar Reforços",
        "ability.call_reinforcements.desc": "Convoca aliados para a luta",
        "ability.prince_slash": "Corte do Príncipe",
        "ability.prince_slash.desc": "Golpe preciso com alto dano",
        "ability.royal_pride": "Orgulho Real",
        "ability.royal_pride.desc": "Aumenta dano e defesa",
        "ability.commander_impale": "Empalar do Comandante",
        "ability.commander_impale.desc": "Ataque pesado com lança",
        "ability.fortress_wall": "Muralha da Fortaleza",
        "ability.fortress_wall.desc": "Grande aumento temporário de armadura",
        "ability.rebel_charge": "Investida Rebelde",
        "ability.rebel_charge.desc": "Avança causando dano pesado",
        "ability.golden_locks": "Cachos Dourados",
        "ability.golden_locks.desc": "Confunde e reduz precisão",
        "ability.throne_claim": "Reivindicar o Trono",
        "ability.throne_claim.desc": "Entra em fúria quando está ferido",
        "ability.stun_strike": "Golpe Atordoante",
        "ability.stun_strike.desc": "Dano com chance de atordoar",
        "ability.curse": "Maldição",
        "ability.curse.desc": "Reduz dano e defesa por alguns segundos",
        "ability.ground_slam": "Impacto no Chão",
        "ability.ground_slam.desc": "Dano em área e atordoamento",
        "ability.ancestral_buff": "Bênção Ancestral",
        "ability.ancestral_buff.desc": "Fortalece aliados próximos",
        "ability.backstab": "Ataque pelas Costas",
        "ability.backstab.desc": "Dano crítico contra alvo distraído",
        "ability.disorient": "Desorientar",
        "ability.disorient.desc": "Reduz velocidade de ataque",

        // Weapons
        "item.weapon.shepherd_staff": "Cajado de Pastor",
        "item.weapon.reinforced_staff": "Cajado Reforçado",
        "item.weapon.shearing_knife": "Faca de Tosquia",
        "item.weapon.wooden_club": "Porrete de Madeira",
        "item.weapon.bronze_dagger": "Adaga de Bronze",
        "item.weapon.short_bronze_sword": "Espada de Bronze Curta",
        "item.weapon.iron_mace": "Maça de Ferro",
        "item.weapon.philistine_sword": "Espada Filisteia",
        "item.weapon.desert_scimitar": "Cimitarra do Deserto",
        "item.weapon.iron_sword": "Espada de Ferro",
        "item.weapon.captain_blade": "Lâmina do Capitão",
        "item.weapon.royal_silver_sword": "Espada Real de Prata",
        "item.weapon.oath_sword": "Espada do Juramento",
        "item.weapon.seraph_blade": "Lâmina Serafim",
        "item.weapon.king_david_sword": "Espada do Rei Davi",
        "item.weapon.reinforced_sling": "Funda Reforçada",
        "item.weapon.bronze_sling": "Funda de Bronze",
        "item.weapon.oak_staff": "Cajado de Carvalho",
        "item.weapon.anointed_staff": "Cajado Ungido",

        // Head
        "item.head.pastor_band": "Faixa de Pastor",
        "item.head.simple_headband": "Faixa de Cabeça Simples",
        "item.head.leather_hood": "Capuz de Couro",
        "item.head.light_bronze_helm": "Elmo de Bronze Leve",
        "item.head.philistine_bronze_helm": "Elmo de Bronze Filisteu",
        "item.head.simple_iron_helmet": "Capacete de Ferro Simples",
        "item.head.desert_helm": "Elmo do Deserto",
        "item.head.bronze_crown": "Coroa de Bronze",
        "item.head.warrior_helm": "Elmo do Guerreiro",
        "item.head.royal_silver_helmet": "Capacete Real de Prata",
        "item.head.faith_helm": "Elmo da Fé",
        "item.head.anointed_iron_crown": "Coroa de Ferro Ungido",
        "item.head.goliath_helm_adapted": "Elmo de Golias (Adaptado)",
        "item.head.seraph_helmet": "Capacete Serafim",
        "item.head.crown_of_the_anointed": "Coroa do Ungido de Deus",

        // Body
        "item.body.shepherd_tunic": "Túnica de Pastor",
        "item.body.tanned_leather_vest": "Veste de Couro Curtido",
        "item.body.reinforced_leather": "Couraça de Couro Reforçado",
        "item.body.lion_skin": "Pele de Leão",
        "item.body.light_chainmail": "Cota de Malha Leve",
        "item.body.bronze_cuirass": "Couraça de Bronze",
        "item.body.scale_armor": "Armadura de Escamas",
        "item.body.philistine_chainmail": "Cota de Malha Filisteia",
        "item.body.desert_cuirass": "Couraça do Deserto",
        "item.body.royal_bronze_armor": "Armadura Real de Bronze",
        "item.body.forged_iron_cuirass": "Couraça de Ferro Forjado",
        "item.body.covenant_breastplate": "Peitoral da Aliança",
        "item.body.general_armor": "Armadura do General",
        "item.body.archangel_cuirass": "Couraça do Arcanjo",
        "item.body.sacred_king_mantle": "Manto Sagrado do Rei",

        // Feet
        "item.feet.leather_sandals": "Sandálias de Couro",
        "item.feet.traveler_sandals": "Sandálias de Viajante",
        "item.feet.desert_sandals": "Sandálias do Deserto",

        // Waist
        "item.waist.rope_belt": "Cinto de Corda",
        "item.waist.leather_belt": "Cinto de Couro",
        "item.waist.warrior_belt": "Cinto de Guerreiro",
        "item.waist.royal_belt": "Cinto Real",

        // Gloves
        "item.gloves.shepherd_wraps": "Ataduras de Pastor",
        "item.gloves.slinger_grips": "Luvas do Fundibulário",
        "item.gloves.anointed_gauntlets": "Manoplas Ungidas",

        // Shield
        "item.shield.wooden_shield": "Escudo de Madeira",
        "item.shield.leather_shield": "Escudo de Couro",
        "item.shield.bronze_round_shield": "Escudo Redondo de Bronze",
        "item.shield.plank_shield": "Escudo de Tábuas",
        "item.shield.iron_buckler": "Broquel de Ferro",
        "item.shield.philistine_bronze_shield": "Escudo de Bronze Filisteu",
        "item.shield.sentinel_shield": "Escudo do Sentinela",
        "item.shield.iron_shield": "Escudo de Ferro",
        "item.shield.desert_shield": "Escudo do Deserto",
        "item.shield.royal_bronze_shield": "Escudo Real de Bronze",
        "item.shield.general_shield": "Escudo do General",
        "item.shield.iron_tower_shield": "Escudo Torre de Ferro",
        "item.shield.covenant_shield": "Escudo do Pacto",
        "item.shield.seraphic_shield": "Escudo Seráfico",
        "item.shield.ark_sacred_shield": "Escudo da Arca Sagrada",

        // Two-hand
        "item.twohand.cedar_staff": "Cajado Grande de Cedro",
        "item.twohand.wooden_spear": "Lança de Madeira",
        "item.twohand.simple_bow": "Arco Simples",
        "item.twohand.bronze_spear": "Lança de Bronze",
        "item.twohand.lumber_axe": "Machado de Lenhador",
        "item.twohand.goliath_sword": "Espada de Golias",
        "item.twohand.composite_war_bow": "Arco Composto de Guerra",
        "item.twohand.iron_halberd": "Alabarda de Ferro",
        "item.twohand.desert_lance": "Lança do Deserto",
        "item.twohand.war_axe": "Machado de Guerra",
        "item.twohand.royal_longbow": "Arco Longo Real",
        "item.twohand.iron_bastard_sword": "Espada Bastarda de Ferro",
        "item.twohand.judgment_lance": "Lança do Juízo",
        "item.twohand.divine_axe": "Machado Divino",
        "item.twohand.moses_staff": "Cajado de Moisés",
        "item.twohand.acacia_staff": "Cajado de Acácia",
        "item.twohand.prophet_staff": "Cajado do Profeta",

        // Settings
        "settings.title": "Configurações",
        "settings.language": "Idioma",
        "settings.sound": "Som",
        "settings.music": "Música",
        "settings.notifications": "Notificações",
        "settings.account": "Conta",
        "settings.logout": "Sair",
        "settings.delete_account": "Excluir conta",
        "settings.confirm_delete_account": "Confirmar exclusão",
        "settings.delete_hint": "Toque novamente para apagar a conta e os dados salvos.",
        "settings.deleting_account": "Excluindo conta...",

        // General
        "general.buy": "Comprar",
        "general.sell": "Vender",
        "general.equip": "Equipar",
        "general.unequip": "Desequipar",
        "general.close": "Fechar",
        "general.confirm": "Confirmar",
        "general.cancel": "Cancelar",
        "general.back": "Voltar",
        "general.ok": "OK",
        "general.continue": "Continuar",
    ]

    // MARK: - English Strings
    static var englishStrings: [String: String] = [
        // Menu
        "menu.start": "Start Journey",
        "menu.continue": "Continue Journey",
        "menu.inventory": "Inventory",
        "menu.shop": "Shop",
        "menu.achievements": "Achievements",
        "menu.ranking": "Ranking",
        "menu.pvp": "PvP Arena",
        "menu.clans": "Clans",
        "menu.challenges": "Weekly Challenges",
        "menu.settings": "Settings",
        "menu.characters": "Characters",
        "menu.inventory_list": "My Items",
        "menu.subtitle": "From pasture to throne",
        "menu.journey_badge": "JOURNEY",
        "menu.chapter1": "Chapter 1",
        "menu.prepare_david": "Prepare David.",
        "menu.battles_won": "%d wins, %d stars",
        "menu.progress": "Progress",
        "menu.actions": "ACTIONS",
        "inventory.equipped": "Equipped",
        "inventory.equipped_short": "Eq.",
        "inventory.empty": "No items in inventory",
        "inventory.empty_slot": "Empty",
        "inventory.item_count.one": "%d item",
        "inventory.item_count.many": "%d items",
        "battle.blessing.choose": "Choose a Blessing",
        "battle.blessing.fallback": "Blessing",
        "battle.blessing.desc_fallback": "Active upgrade",
        "battle.blessing.strength": "Strength Blessing",
        "battle.blessing.strength.desc": "+15% Damage",
        "battle.blessing.faith_shield": "Shield of Faith",
        "battle.blessing.faith_shield.desc": "+10 Armor",
        "battle.blessing.swift_hands": "Swift Hands",
        "battle.blessing.swift_hands.desc": "+15% Attack Speed",
        "battle.blessing.bronze_skin": "Bronze Skin",
        "battle.blessing.bronze_skin.desc": "+20 Max HP",
        "battle.blessing.eagle_eye": "Eagle Eye",
        "battle.blessing.eagle_eye.desc": "+10% Critical",

        // Language Selection
        "lang.title": "Choose your language",
        "lang.select": "Select",

        // Login
        "login.title": "David: The Anointed",
        "login.google": "Sign in with Google",
        "login.apple": "Sign in with Apple",
        "login.loading": "Loading...",
        "login.loading_google": "Signing in with Google...",
        "login.loading_apple": "Signing in with Apple...",

        // Maps
        "map.stage": "Stage",
        "map.bethlehem_fields": "Fields of Bethlehem",
        "map.valley_of_elah": "Valley of Elah",
        "map.saul_court": "Saul's Court",
        "map.en_gedi": "Desert of En-Gedi",
        "map.philistine_land": "Land of the Philistines",
        "map.jerusalem_siege": "Siege of Jerusalem",
        "map.throne_israel": "Throne of Israel",

        // Battles Map 1
        "battle.wolf_pack": "Wolf Pack",
        "battle.night_invaders": "Night Invaders",
        "battle.mountain_trail": "Mountain Trail",
        "battle.lion_boss": "The Lion of Bethlehem",

        // Battles Map 2
        "battle.mountain_bear": "The Mountain Bear",
        "battle.philistine_scouts": "Philistine Scouts",
        "battle.advance_guard": "Advance Guard",
        "battle.goliath_boss": "Goliath the Giant",

        // Battles Map 3
        "battle.royal_hall": "Saul's Royal Hall",
        "battle.conspiracy": "Palace Conspiracy",
        "battle.betrayal": "Saul's Betrayal",
        "battle.saul_boss": "Saul, the Tormented King",
        "battle.burning_dunes": "Burning Dunes",
        "battle.cave_path": "Cave Path",
        "battle.en_gedi_oasis": "En-Gedi Oasis",
        "battle.general_boss": "Saul's General",
        "battle.philistine_border": "Philistine Border",
        "battle.road_to_gath": "Road to Gath",
        "battle.war_camp": "War Camp",
        "battle.prince_boss": "Philistine Prince",
        "battle.jebus_walls": "Walls of Jebus",
        "battle.water_tunnels": "Water Tunnels",
        "battle.city_gates": "City Gates",
        "battle.commander_boss": "Jebusite Commander",
        "battle.jerusalem_rebellion": "Jerusalem Rebellion",
        "battle.kidron_path": "Kidron Path",
        "battle.civil_war": "Civil War",
        "battle.absalom_boss": "Absalom, the Rebel",

        // Enemies
        "enemy.grey_wolf": "Grey Wolf",
        "enemy.alpha_wolf": "Alpha Wolf",
        "enemy.rabid_fox": "Rabid Fox",
        "enemy.hungry_jackal": "Hungry Jackal",
        "enemy.wild_boar": "Wild Boar",
        "enemy.venomous_snake": "Venomous Snake",
        "enemy.hunting_eagle": "Hunting Eagle",
        "enemy.giant_scorpion": "Giant Scorpion",
        "enemy.pack_hyena": "Pack Hyena",
        "enemy.hyena_pup": "Hyena Pup",
        "enemy.lion_boss": "Lion of Bethlehem",
        "enemy.bear_cub": "Bear Cub",
        "enemy.brown_bear": "Brown Bear",
        "enemy.goliath": "Goliath",
        "enemy.philistine_scout_spear": "Philistine Scout (Spear)",
        "enemy.philistine_scout_bow": "Philistine Scout (Bow)",
        "enemy.philistine_scout_shield": "Philistine Scout (Shield)",
        "enemy.philistine_soldier": "Philistine Soldier",
        "enemy.philistine_archer": "Philistine Archer",
        "enemy.philistine_elite": "Elite Philistine Soldier",
        "enemy.philistine_healer": "Philistine Healer",
        "enemy.saul_guard": "Royal Guard",
        "enemy.saul_archer": "Royal Archer",
        "enemy.saul_spearman": "Royal Spearman",
        "enemy.saul_advisor": "Royal Advisor",
        "enemy.saul_mad": "King Saul",
        "enemy.saul_general": "Saul's General",
        "enemy.desert_bandit": "Desert Bandit",
        "enemy.bandit_archer": "Bandit Archer",
        "enemy.giant_spider": "Giant Spider",
        "enemy.desert_stalker": "Desert Stalker",
        "enemy.philistine_heavy_guard": "Philistine Heavy Guard",
        "enemy.philistine_war_archer": "Philistine War Archer",
        "enemy.philistine_giant": "Philistine Giant",
        "enemy.philistine_priest": "Philistine Priest",
        "enemy.philistine_prince": "Philistine Prince",
        "enemy.jebusite_defender": "Jebusite Defender",
        "enemy.jebusite_slinger": "Jebusite Slinger",
        "enemy.jebusite_elite": "Jebusite Elite",
        "enemy.jebusite_shaman": "Jebusite Shaman",
        "enemy.jebusite_commander": "Jebusite Commander",
        "enemy.absalom_rebel": "Absalom Rebel",
        "enemy.absalom_assassin": "Absalom Assassin",
        "enemy.absalom_knight": "Absalom Knight",
        "enemy.absalom_tactician": "Absalom Tactician",
        "enemy.absalom": "Absalom",

        // Food
        "food.barley_bread": "Barley Bread",
        "food.water_skin": "Drinking Water",
        "food.grapes": "Grape Bunch",
        "food.grape_juice": "Grape Juice",
        "food.fresh_figs": "Fresh Figs",
        "food.dried_figs": "Dried Figs",
        "food.olives": "Olives in Oil",
        "food.honey_bread": "Honey Bread",
        "food.pomegranate": "Pomegranate",
        "food.goat_cheese": "Goat Cheese",
        "food.dates": "Dates",
        "food.cooked_lentils": "Cooked Lentils",
        "food.roasted_fish": "Roasted Fish",
        "food.raisin_cake": "Raisin Cake",
        "food.roasted_lamb": "Roasted Lamb",
        "food.manna": "Angel's Bread (Manna)",
        "food.kings_feast": "King's Feast",
        "food.celestial_banquet": "Celestial Banquet",
        "food.water_skin.buff": "+3% Dodge for 8s",
        "food.grape_juice.buff": "+5% Crit Chance for 10s",
        "food.dried_figs.buff": "Removes poison",
        "food.olives.buff": "+5% Dodge for 10s",
        "food.pomegranate.buff": "+10% Attack Speed for 8s",
        "food.goat_cheese.buff": "+5 Armor for 10s",
        "food.dates.buff": "+8% Crit Chance for 10s",
        "food.roasted_fish.buff": "+3% Life Steal for 15s",
        "food.raisin_cake.buff": "Removes debuffs",
        "food.roasted_lamb.buff": "+10% Damage for 10s",
        "food.manna.buff": "+5% all stats for 10s",
        "food.kings_feast.buff": "+15% Damage, +10 Armor for 12s",
        "food.celestial_banquet.buff": "Full heal + all buffs for 8s",

        // Characters
        "character.davi": "David",
        "character.bigJ": "JV",
        "character.sansao": "Samson",
        "character.josue": "FaithTech",
        "character.debora": "Deborah",
        "character.elias": "Elijah",
        "character.gideao": "Gideon",
        "character.stats_title": "Character Sheet",
        "character.passive_bonus": "Passive bonus",
        "character.active": "ACTIVE",
        "character.unlocked": "UNLOCKED",
        "character.locked": "LOCKED",
        "character.select": "Select",
        "character.required_map": "Requires stage",
        "character.balanced": "Balanced",
        "character.unlocked_message": "Character unlocked in your roster.",
        "character.selected_message": "Character selected for the journey.",
        "stat.hp": "HP",
        "stat.damage": "Damage",
        "stat.damage_bonus": "Damage",
        "stat.armor": "Armor",
        "stat.crit_chance": "Crit",
        "stat.crit_damage": "Crit Damage",
        "stat.attack_speed": "Attack Speed",
        "stat.life_steal": "Life Steal",
        "stat.dodge_melee": "Melee Dodge",
        "stat.dodge_ranged": "Ranged Dodge",
        "stat.run_speed": "Speed",

        // HUD
        "hud.attack": "ATTACK",
        "hud.defense": "DEFENSE",
        "hud.dodge": "DODGE",
        "hud.damage": "Damage",
        "hud.crit_chance": "Crit Chance",
        "hud.crit_damage": "Crit Damage",
        "hud.hp_max": "Max HP",
        "hud.max_armor": "Max Armor",
        "hud.melee": "Melee",
        "hud.ranged": "Ranged",
        "hud.victory": "VICTORY!",
        "hud.defeat": "DEFEAT",
        "hud.level": "Level",
        "hud.gold": "Gold",
        "hud.rubies": "Rubies",
        "battle.defeat_hint": "Upgrade David and try again",
        "battle.partial_reward": "You earned",

        // Item Actions & Slots
        "item.action.equip": "Equip",
        "item.action.unequip": "Unequip",
        "item.type": "Type",
        "shop.owned": "Owned",
        "shop.food": "Food",
        "shop.filter.all": "All",
        "shop.filter.weapon": "Weapon",
        "shop.filter.shield": "Shield",
        "shop.chests": "Rewards",
        "shop.rewards": "Rewards",
        "shop.reward.battle.title": "Battle",
        "shop.reward.battle.desc": "Clear stages to earn gold, XP, and item chances.",
        "shop.reward.items.title": "Items",
        "shop.reward.items.desc": "Drops come from stage rewards, not random purchases.",
        "shop.reward.shop.title": "Clear Shop",
        "shop.reward.shop.desc": "Buy specific gear, food, and characters directly.",
        "shop.reward.footer": "There are no purchasable chests or paid random draws. All gold is earned by playing.",
        "shop.chest.common": "Common Reward",
        "shop.chest.rare": "Rare Reward",
        "shop.chest.legendary": "Legendary Reward",
        "shop.chest.common.desc": "Battle bonus",
        "shop.chest.rare.desc": "Stage drop",
        "shop.chest.legendary.desc": "Rare achievement",
        "shop.chest.reward": "You received",
        "shop.chest.empty": "No new items",
        "shop.chest.empty.desc": "You already own every possible item.",
        "shop.not_enough_gold": "Not enough gold",
        "shop.not_enough_gold.desc": "Win battles to earn more gold.",
        "shop.sell.title": "Sell item",
        "shop.sell.confirm": "Sell for",
        "shop.sell.done": "Sold",
        "shop.sell.done.desc": "%@ sold for %d gold.",
        "item.rarity.common": "Common",
        "item.rarity.uncommon": "Uncommon",
        "item.rarity.rare": "Rare",
        "item.rarity.epic": "Epic",
        "item.rarity.legendary": "Legendary",
        "item.slot.head": "Head",
        "item.slot.body": "Body",
        "item.slot.feet": "Feet",
        "item.slot.waist": "Belt",
        "item.slot.mainHand": "Main Hand",
        "item.slot.offHand": "Off Hand",
        "item.slot.twoHand": "Two Hands",
        "item.slot.necklace": "Necklace",
        "item.slot.ring1": "Ring 1",
        "item.slot.ring2": "Ring 2",
        "item.slot.gloves": "Gloves",
        "item.slot.short.head": "HD",
        "item.slot.short.body": "BDY",
        "item.slot.short.feet": "FT",
        "item.slot.short.waist": "BLT",
        "item.slot.short.mainHand": "MH",
        "item.slot.short.offHand": "OH",
        "item.slot.short.twoHand": "2H",
        "item.slot.short.necklace": "NEC",
        "item.slot.short.ring1": "R1",
        "item.slot.short.ring2": "R2",
        "item.slot.short.gloves": "GLV",

        // Abilities
        "ability.bite": "Bite",
        "ability.bite.desc": "Damage + light bleed",
        "ability.howl": "Howl",
        "ability.howl.desc": "Buff allies attack +20%",
        "ability.charge": "Charge",
        "ability.charge.desc": "AoE damage + stun 1s",
        "ability.venom": "Venom",
        "ability.venom.desc": "DoT for 3s",
        "ability.dive": "Dive",
        "ability.dive.desc": "Aerial attack, ignores armor",
        "ability.sting": "Sting",
        "ability.sting.desc": "Poison + slow",
        "ability.summon_pup": "Summon Pup",
        "ability.summon_pup.desc": "Summons 1 Hyena Pup",
        "ability.paw_swipe": "Paw Swipe",
        "ability.paw_swipe.desc": "Claw strike",
        "ability.roar": "Roar",
        "ability.roar.desc": "Reduces attack -15% for 5s",
        "ability.death_leap": "Death Leap",
        "ability.death_leap.desc": "Massive damage + stun",
        "ability.bear_hug": "Bear Hug",
        "ability.bear_hug.desc": "Grabs and deals continuous damage 3s",
        "ability.claw_strike": "Claw Strike",
        "ability.claw_strike.desc": "Damage + reduces armor -5",
        "ability.block": "Block",
        "ability.block.desc": "+50% temporary armor",
        "ability.fire_arrow": "Flaming Arrow",
        "ability.fire_arrow.desc": "DoT 2s",
        "ability.counter": "Counter-Attack",
        "ability.counter.desc": "Reflects 20% damage",
        "ability.heal_allies": "Heal Allies",
        "ability.heal_allies.desc": "+15 HP allies every 5s",
        "ability.spear_throw": "Spear Throw",
        "ability.spear_throw.desc": "High ranged damage",
        "ability.giant_shield": "Giant Shield",
        "ability.giant_shield.desc": "Blocks next attack",
        "ability.stomp": "Stomp",
        "ability.stomp.desc": "AoE + stun 2s",
        "ability.giant_fury": "Giant's Fury",
        "ability.giant_fury.desc": "+30% damage + charge",
        "ability.javelin_throw": "Javelin Throw",
        "ability.javelin_throw.desc": "Piercing ranged damage",
        "ability.mad_fury": "Mad Fury",
        "ability.mad_fury.desc": "Faster attacks for a short time",
        "ability.strategic_strike": "Strategic Strike",
        "ability.strategic_strike.desc": "High damage against weakened targets",
        "ability.call_reinforcements": "Call Reinforcements",
        "ability.call_reinforcements.desc": "Summons allies into the fight",
        "ability.prince_slash": "Prince Slash",
        "ability.prince_slash.desc": "Precise high-damage strike",
        "ability.royal_pride": "Royal Pride",
        "ability.royal_pride.desc": "Increases damage and defense",
        "ability.commander_impale": "Commander Impale",
        "ability.commander_impale.desc": "Heavy spear attack",
        "ability.fortress_wall": "Fortress Wall",
        "ability.fortress_wall.desc": "Large temporary armor increase",
        "ability.rebel_charge": "Rebel Charge",
        "ability.rebel_charge.desc": "Charges forward with heavy damage",
        "ability.golden_locks": "Golden Locks",
        "ability.golden_locks.desc": "Confuses and reduces accuracy",
        "ability.throne_claim": "Throne Claim",
        "ability.throne_claim.desc": "Enters fury when wounded",
        "ability.stun_strike": "Stun Strike",
        "ability.stun_strike.desc": "Damage with a chance to stun",
        "ability.curse": "Curse",
        "ability.curse.desc": "Reduces damage and defense for a few seconds",
        "ability.ground_slam": "Ground Slam",
        "ability.ground_slam.desc": "Area damage and stun",
        "ability.ancestral_buff": "Ancestral Blessing",
        "ability.ancestral_buff.desc": "Empowers nearby allies",
        "ability.backstab": "Backstab",
        "ability.backstab.desc": "Critical damage against a distracted target",
        "ability.disorient": "Disorient",
        "ability.disorient.desc": "Reduces attack speed",

        // Weapons
        "item.weapon.shepherd_staff": "Shepherd's Staff",
        "item.weapon.reinforced_staff": "Reinforced Staff",
        "item.weapon.shearing_knife": "Shearing Knife",
        "item.weapon.wooden_club": "Wooden Club",
        "item.weapon.bronze_dagger": "Bronze Dagger",
        "item.weapon.short_bronze_sword": "Short Bronze Sword",
        "item.weapon.iron_mace": "Iron Mace",
        "item.weapon.philistine_sword": "Philistine Sword",
        "item.weapon.desert_scimitar": "Desert Scimitar",
        "item.weapon.iron_sword": "Iron Sword",
        "item.weapon.captain_blade": "Captain's Blade",
        "item.weapon.royal_silver_sword": "Royal Silver Sword",
        "item.weapon.oath_sword": "Oath Sword",
        "item.weapon.seraph_blade": "Seraph Blade",
        "item.weapon.king_david_sword": "King David's Sword",
        "item.weapon.reinforced_sling": "Reinforced Sling",
        "item.weapon.bronze_sling": "Bronze Sling",
        "item.weapon.oak_staff": "Oak Staff",
        "item.weapon.anointed_staff": "Anointed Staff",

        // Head
        "item.head.pastor_band": "Shepherd's Band",
        "item.head.simple_headband": "Simple Headband",
        "item.head.leather_hood": "Leather Hood",
        "item.head.light_bronze_helm": "Light Bronze Helm",
        "item.head.philistine_bronze_helm": "Philistine Bronze Helm",
        "item.head.simple_iron_helmet": "Simple Iron Helmet",
        "item.head.desert_helm": "Desert Helm",
        "item.head.bronze_crown": "Bronze Crown",
        "item.head.warrior_helm": "Warrior Helm",
        "item.head.royal_silver_helmet": "Royal Silver Helmet",
        "item.head.faith_helm": "Helm of Faith",
        "item.head.anointed_iron_crown": "Anointed Iron Crown",
        "item.head.goliath_helm_adapted": "Goliath's Helm (Adapted)",
        "item.head.seraph_helmet": "Seraph Helmet",
        "item.head.crown_of_the_anointed": "Crown of the Anointed",

        // Body
        "item.body.shepherd_tunic": "Shepherd's Tunic",
        "item.body.tanned_leather_vest": "Tanned Leather Vest",
        "item.body.reinforced_leather": "Reinforced Leather",
        "item.body.lion_skin": "Lion Skin",
        "item.body.light_chainmail": "Light Chainmail",
        "item.body.bronze_cuirass": "Bronze Cuirass",
        "item.body.scale_armor": "Scale Armor",
        "item.body.philistine_chainmail": "Philistine Chainmail",
        "item.body.desert_cuirass": "Desert Cuirass",
        "item.body.royal_bronze_armor": "Royal Bronze Armor",
        "item.body.forged_iron_cuirass": "Forged Iron Cuirass",
        "item.body.covenant_breastplate": "Covenant Breastplate",
        "item.body.general_armor": "General's Armor",
        "item.body.archangel_cuirass": "Archangel Cuirass",
        "item.body.sacred_king_mantle": "Sacred King's Mantle",

        // Feet
        "item.feet.leather_sandals": "Leather Sandals",
        "item.feet.traveler_sandals": "Traveler Sandals",
        "item.feet.desert_sandals": "Desert Sandals",

        // Waist
        "item.waist.rope_belt": "Rope Belt",
        "item.waist.leather_belt": "Leather Belt",
        "item.waist.warrior_belt": "Warrior Belt",
        "item.waist.royal_belt": "Royal Belt",

        // Gloves
        "item.gloves.shepherd_wraps": "Shepherd Wraps",
        "item.gloves.slinger_grips": "Slinger's Grips",
        "item.gloves.anointed_gauntlets": "Anointed Gauntlets",

        // Shield
        "item.shield.wooden_shield": "Wooden Shield",
        "item.shield.leather_shield": "Leather Shield",
        "item.shield.bronze_round_shield": "Bronze Round Shield",
        "item.shield.plank_shield": "Plank Shield",
        "item.shield.iron_buckler": "Iron Buckler",
        "item.shield.philistine_bronze_shield": "Philistine Bronze Shield",
        "item.shield.sentinel_shield": "Sentinel Shield",
        "item.shield.iron_shield": "Iron Shield",
        "item.shield.desert_shield": "Desert Shield",
        "item.shield.royal_bronze_shield": "Royal Bronze Shield",
        "item.shield.general_shield": "General's Shield",
        "item.shield.iron_tower_shield": "Iron Tower Shield",
        "item.shield.covenant_shield": "Covenant Shield",
        "item.shield.seraphic_shield": "Seraphic Shield",
        "item.shield.ark_sacred_shield": "Ark Sacred Shield",

        // Two-hand
        "item.twohand.cedar_staff": "Cedar Grand Staff",
        "item.twohand.wooden_spear": "Wooden Spear",
        "item.twohand.simple_bow": "Simple Bow",
        "item.twohand.bronze_spear": "Bronze Spear",
        "item.twohand.lumber_axe": "Lumber Axe",
        "item.twohand.goliath_sword": "Goliath's Sword",
        "item.twohand.composite_war_bow": "Composite War Bow",
        "item.twohand.iron_halberd": "Iron Halberd",
        "item.twohand.desert_lance": "Desert Lance",
        "item.twohand.war_axe": "War Axe",
        "item.twohand.royal_longbow": "Royal Longbow",
        "item.twohand.iron_bastard_sword": "Iron Bastard Sword",
        "item.twohand.judgment_lance": "Judgment Lance",
        "item.twohand.divine_axe": "Divine Axe",
        "item.twohand.moses_staff": "Moses' Staff",
        "item.twohand.acacia_staff": "Acacia Staff",
        "item.twohand.prophet_staff": "Prophet's Staff",

        // Settings
        "settings.title": "Settings",
        "settings.language": "Language",
        "settings.sound": "Sound",
        "settings.music": "Music",
        "settings.notifications": "Notifications",
        "settings.account": "Account",
        "settings.logout": "Sign Out",
        "settings.delete_account": "Delete Account",
        "settings.confirm_delete_account": "Confirm Deletion",
        "settings.delete_hint": "Tap again to delete the account and saved data.",
        "settings.deleting_account": "Deleting account...",

        // General
        "general.buy": "Buy",
        "general.sell": "Sell",
        "general.equip": "Equip",
        "general.unequip": "Unequip",
        "general.close": "Close",
        "general.confirm": "Confirm",
        "general.cancel": "Cancel",
        "general.back": "Back",
        "general.ok": "OK",
        "general.continue": "Continue",
    ]
}
